AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Framework Native Image

Globals:
  Function:
    Tracing: Active
    CodeUri: target/function.zip
    Handler: not.used.in.provided.runtime
    Runtime: provided.al2
    Architectures:
      - arm64
    Timeout: 10
    MemorySize: 2048
    Environment:
      Variables:
        PRODUCT_TABLE_NAME: !Ref ProductsTable
        DISABLE_SIGNAL_HANDLERS: true

Resources:
  PutProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "awsdevday2023tokyo-sls-framework-native-image"
      Environment:
        Variables:
          quarkus_lambda_handler: createProduct
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Events:
        PutRequest:
          Type: HttpApi
          Properties:
            Path: /products/{id}
            Method: put

  PutProductFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${PutProductFunction}"
      RetentionInDays: 7

  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: 'PK'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'PK'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for Quarkus sample function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/products"
